<<<<<<< HEAD
# Generated by Django 5.1.2 on 2025-04-20 23:17

import django.db.models.deletion
import uuid
from django.conf import settings
=======
# Generated by Django 5.1.7 on 2025-04-18 22:24

import uuid
>>>>>>> dfc400d6057bd966c93099f7736d4b1afa04efbe
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
=======
>>>>>>> dfc400d6057bd966c93099f7736d4b1afa04efbe
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('type', models.CharField(max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
<<<<<<< HEAD
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
=======
>>>>>>> dfc400d6057bd966c93099f7736d4b1afa04efbe
            ],
        ),
    ]
