<<<<<<< HEAD
# Generated by Django 5.1.2 on 2025-04-20 23:17
=======
# Generated by Django 5.1.7 on 2025-04-18 22:24
>>>>>>> dfc400d6057bd966c93099f7736d4b1afa04efbe

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
        ('orders', '0001_initial'),
        ('reservations', '0001_initial'),
<<<<<<< HEAD
=======
        ('users', '0001_initial'),
>>>>>>> dfc400d6057bd966c93099f7736d4b1afa04efbe
    ]

    operations = [
        migrations.AddField(
            model_name='order',
<<<<<<< HEAD
=======
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='users.customer'),
        ),
        migrations.AddField(
            model_name='order',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='users.staff'),
        ),
        migrations.AddField(
            model_name='order',
>>>>>>> dfc400d6057bd966c93099f7736d4b1afa04efbe
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='reservations.table'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='menu.menuitem'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order'),
        ),
        migrations.AddField(
            model_name='orderitemoption',
            name='menu_item_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_item_options', to='menu.menuitemoption'),
        ),
        migrations.AddField(
            model_name='orderitemoption',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='orders.orderitem'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='orders.orderitemstatus'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='orders.orderstatus'),
        ),
    ]
