<<<<<<< HEAD
# Generated by Django 5.1.2 on 2025-04-20 23:17

import django.db.models.deletion
=======
# Generated by Django 5.1.7 on 2025-04-18 22:24

>>>>>>> dfc400d6057bd966c93099f7736d4b1afa04efbe
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('users', '0001_initial'),
=======
>>>>>>> dfc400d6057bd966c93099f7736d4b1afa04efbe
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
=======
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reservation_date', models.DateTimeField()),
                ('duration', models.IntegerField(help_text='Duration in minutes')),
                ('group_size', models.IntegerField()),
                ('special_requests', models.TextField(blank=True, null=True)),
                ('confirmation_code', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
>>>>>>> dfc400d6057bd966c93099f7736d4b1afa04efbe
            name='ReservationStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(max_length=20)),
                ('qr_code_url', models.URLField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
<<<<<<< HEAD
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='users.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reservation_date', models.DateTimeField()),
                ('duration', models.IntegerField(help_text='Duration in minutes')),
                ('group_size', models.IntegerField()),
                ('special_requests', models.TextField(blank=True, null=True)),
                ('confirmation_code', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='users.customer')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='reservations.reservationstatus')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='reservations.table')),
=======
>>>>>>> dfc400d6057bd966c93099f7736d4b1afa04efbe
            ],
        ),
    ]
