# Generated by Django 5.1.7 on 2025-08-31 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0004_table_is_reserved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='is_reserved',
        ),
    ]
