# Generated by Django 5.1.7 on 2025-05-30 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitemoption',
            name='image_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='menuitemoption',
            name='is_available',
            field=models.IntegerField(default=1),
        ),
    ]
