# Generated by Django 5.1.7 on 2025-05-18 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='calories',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='preparation_time',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='is_promotion',
            field=models.BooleanField(default=False),
        ),
    ]
