# Generated by Django 5.1.7 on 2025-05-25 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_remove_menuitem_calories_remove_menuitem_ingredients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('entradas', 'Entradas'), ('plato_fuerte', 'Plato Fuerte'), ('postres', 'Postres'), ('bebidas', 'Bebidas'), ('combo', 'Combo')], max_length=50),
        ),
        migrations.DeleteModel(
            name='MenuCategory',
        ),
    ]
