# Generated by Django 5.1.7 on 2025-05-30 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('staff', 'staff'), ('customer', 'customer')], default='customer', max_length=10),
        ),
    ]
