# Generated by Django 5.1.7 on 2025-05-30 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('staff', 'staff'), ('customer', 'customer')], default='customer', max_length=20),
        ),
    ]
